export enum Action {
  ALL = 'ALL',
  EDIT_ASSIGNMENTS = 'EDIT_ASSIGNMENTS',
  EDIT_LOCALES = 'EDIT_LOCALES',
  EDIT_OUTPUTS = 'EDIT_OUTPUTS',
  EDIT_USERS = 'EDIT_USERS',
  TRANSLATE_ROWS = 'TRANSLATE_ROWS',
}
