name: Map data upload (cronjob)

on:
  workflow_dispatch:

  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "*/30 * * * *" # Run every 30 minutes

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip" # caching pip dependencies

      - run: pip install -r requirements.txt

      - name: Run parsers
        run: |
          cd data
          mkdir to_upload

          python map-parsers/all_parser.py ./to_upload/latest.json
          gzip -9 -c ./to_upload/latest.json > "./to_upload/`date +%Y-%m-%d_%H-%M-%S`.json.gz"

      - name: Sync JSON files
        run: aws s3 sync ./data/to_upload/. s3://cdn.afetbilgi.com/maps
